name: passave
description: "Passave is a secure, cross-platform password manager with KeePass compatibility, multi-device sync, and autofill support."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  uuid:
  cryptography:
  flutter_secure_storage:
  local_auth:
  hive:
  hive_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons:

flutter_icons:
  android: true
  image_path: "assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/